### ISSUE TITLE
Debug specific RSpec test

### ISSUE THREAD

**Issue by olimorris** [suketa/nvim-dap-ruby#17]
One of the great features of RSpec is that you can run specific tests by passing in the `[filename]:[linenumber]` and it will figure out what to run.

Sometimes in a test suite I may have loads of tests (many even failing) and I just want to test one. Currently there is no way to do it without running the whole RSpec test suite or running the file.

I looked at modifying my config to pass in `vim.fn.line(".")` but that seems to return `1` always. I note that `nvim-dap` doesn't [support line numbers as variables](https://github.com/mfussenegger/nvim-dap/blob/f4a3be57f61893cffa1e22aa5e1e7bded495fcf2/doc/dap.txt#L219) but wondered if you knew of a way around this?

**Comment by suketa** [comment]
@olimorris 
Does #21 work?

**Comment by hahuang65** [comment]
Will chime in here... this works for me.

**Comment by olimorris** [comment]
Should have closed this long ago. Thanks!
