### ISSUE TITLE
The session remains active even after the last program line is executed

### ISSUE THREAD

**Issue by oats4goats** [suketa/nvim-dap-ruby#8]
First of all, thanks for getting `rdbg` working with `nvim-dap`. It's a great help!

I have a minor issue with the session remaining active even after the last step is executed so I was wondering if you have bumped into the same problem and whether you fixed it or not?

As of now, I have to disconnect every time to get a new session running which is a bit weird. And it works just fine in VS Code (disconnects after the last step) so probably it's not about the debugger itself.

Thanks for your help!

**Comment by suketa** [comment]
I have same issue, but I haven't found the solution...

**Comment by oats4goats** [comment]
Thanks! Don't know why, but it freaks me out a bit so I'm trying to investigate :) I'll try to raise an issue in `mfussenegger/nvim-dap` because the remote debugging with `rdbg` in two terminals works just fine. It should be something about dap, I suppose, but I don't have the knowledge to unravel it.

**Comment by oats4goats** [comment]
Just wanted to let you know that the issue's been fixed by `mfussenegger` in [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap/issues/429) though the root cause seems to be in [ruby/debug](https://github.com/ruby/debug/issues/523).

**Comment by suketa** [comment]
Thank you for your information. I close this issue.
