### ISSUE TITLE
Rspec debugging is not running correctly.

### ISSUE THREAD

**Issue by gardealra** [suketa/nvim-dap-ruby#9]
Foremost, thanks a lot for this plugin! 

I am trying to debug a spec file and after setting a couple of break points, I select the option “run current spec file”. Instead of opening the test, my DAP opens the file :

`#1 /Users/rafaelgarciadealba/.asdf/installs/ruby/3.0.3/bin/rspec:9:in `<main>':`
![Screenshot 2022-03-16 at 16 55 22](https://user-images.githubusercontent.com/71753108/158633055-c8624731-99fb-4576-9ff9-320b4cc62360.png)

And what I would like to open is the test, instead of this file. 

I have no idea what I am doing wrong. Any help would be appreciated.

**Comment by suketa** [comment]
I think debugger starting correctly and stopped line 20. (I don't know the reason why)

Could you try again `:lua require'dap'.continue()` ? 

or

1. `:lua require'dap'.repl.open()`
2. move cursor into opened buffer
3. type `i` (move input mode and show `dap>` console)
4. type `.c`

Pls check https://github.com/mfussenegger/nvim-dap for more detail operation.

**Comment by gardealra** [comment]
Thanks for your reply. You are right, I was just checking the debugger logs, and they are running correctly. When I try to continue within the repl or with `lua require'dap'.continue()` it exits the debugging session and is pointing at some rails requirements. I think this is my problem, since as mentioned in the readme rails is not supported. I would love to collaborate with you and maybe make it also extensible for rails and rake. Let me know if this is possible. I will close this because it's cleared.
